from typing import Optional, Dict, Any
from pydantic import BaseModel, Field, ValidationError
import random
from tools.utils import load_data, save_data, create_response_json, handle_tool_error

class BookTripInput(BaseModel):
    booking_type: str = Field(description="Type of booking (e.g., 'flight', 'hotel', 'package').")
    details: Optional[Dict[str, Any]] = Field(default={}, description="Optional details about the booking.")

def book_trip(*args, **kwargs) -> str:
    """
    Unified booking tool to book flights, hotels, or packages.
    """
    try:
        payload_candidate: Optional[dict] = None

        if 'payload' in kwargs:
            payload_candidate = kwargs.pop('payload')

        if args:
            if len(args) >= 2 and isinstance(args[0], dict) and isinstance(args[1], dict):
                payload_candidate = payload_candidate or args[1]
            else:
                for a in args:
                    if isinstance(a, dict):
                        if payload_candidate is None:
                            payload_candidate = a

        merged: Dict[str, Any] = {}
        if payload_candidate:
            if not isinstance(payload_candidate, dict):
                return create_response_json("payload must be a dict", status=False)
            merged.update(payload_candidate)

        merged.update(kwargs)

        try:
            validated = BookTripInput(**merged)
        except ValidationError as e:
            # Fallback if arguments are passed directly instead of inside payload
            # This handles cases where the agent might pass arguments individually
            if 'booking_type' in merged:
                validated = BookTripInput(booking_type=merged['booking_type'], details=merged.get('details', {}))
            else:
                 return create_response_json(f"Invalid payload: {e}", status=False)


        booking_type = validated.booking_type
        details = validated.details

        # Generate dummy booking data
        booking_id = f"BKG-RANDOM-{random.randint(1000, 9999)}"
        booking_record = {
            "booking_id": booking_id,
            "type": booking_type,
            "status": "Confirmed",
            "details": details, # Store whatever details were passed
            "dummy_data": "This is a dummy booking generated by book_trip"
        }

        # Persist booking
        bookings = load_data("bookings.json")
        if not isinstance(bookings, list):
            bookings = []
        bookings.append(booking_record)
        save_data("bookings.json", bookings)

        return create_response_json(
            "Connecting you to an Agent...",
            status=True,
            data=booking_record
        )

    except Exception as ex:
        return handle_tool_error(ex, "book_trip")
